### ISSUE TITLE
OpenCamera fail through DLFroxyActivity on sdcard apk

### ISSUE THREAD

**Issue by Anjon-github** [singwhatiwanna/dynamic-load-apk#103]
10-06 17:10:33.053: W/System.err(15995): java.lang.RuntimeException: Fail to connect to camera service
10-06 17:10:33.063: W/System.err(15995): 	at android.hardware.Camera.native_setup(Native Method)
10-06 17:10:33.063: W/System.err(15995): 	at android.hardware.Camera.<init>(Camera.java:329)
10-06 17:10:33.063: W/System.err(15995): 	at android.hardware.Camera.open(Camera.java:287)

**Comment by Anjon-github** [comment]
已经找到原因了，是自己宿主activity没有注册相机权限导致
