### ISSUE TITLE
加载插件报错java.lang.IllegalStateException: Zip file closed

### ISSUE THREAD

**Issue by kaiyuanshengshichangan** [singwhatiwanna/dynamic-load-apk#111]
Process: com.example.dynamicliveapk, PID: 18685
                                                                            java.lang.IllegalStateException: Zip file closed
                                                                                at java.util.zip.ZipFile.checkNotClosed(ZipFile.java:215)
                                                                                at java.util.zip.ZipFile.getEntry(ZipFile.java:264)
                                                                                at java.util.zip.ZipFile.getInputStream(ZipFile.java:288)
                                                                                at com.ryg.utils.SoLibManager$CopySoTask.writeSoFile2LibDir(SoLibManager.java:172)
                                                                                at com.ryg.utils.SoLibManager$CopySoTask.run(SoLibManager.java:210)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:818)

**Comment by kaiyuanshengshichangan** [comment]
有人知道是什么原因吗

**Comment by kaedea** [comment]
提前关闭ZipFile对象了，这是项目的一个BUG

**Comment by kaiyuanshengshichangan** [comment]
是啊，我现在是直接把这句话注释掉了，不知道对不对，但是运行正常

**Comment by ray0807** [comment]
@kaiyuanshengshichangan   我也遇到了这个问题，还有就是拷贝so出现 is  too small 等问题
