### ISSUE TITLE
加载包含so文件的插件报错XXXX.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by kaiyuanshengshichangan** [singwhatiwanna/dynamic-load-apk#113]
插件中包含so文件，单独运行插件程序正常没问题，但是通过宿主调用插件就报错了
 FATAL EXCEPTION: main
                                                                            Process: com.example.dynamicliveapk, PID: 22951
                                                                            java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.example.dynamicliveapk/app_pluginlib/libstlport_shared.so" is 32-bit instead of 64-bit
                                                                                at java.lang.Runtime.loadLibrary(Runtime.java:383)
                                                                                at java.lang.System.loadLibrary(System.java:997)
                                                                                at com.gensee.utils.GenseeLog.loadlibrary(GenseeLog.java:606)
                                                                                at com.gensee.utils.GenseeLog.initLog(GenseeLog.java:85)
                                                                                at com.gensee.utils.GenseeLog.initLog(GenseeLog.java:67)
                                                                                at com.gensee.net.AbsRoomSite.initLog(AbsRoomSite.java:506)
                                                                                at com.gensee.net.AbsRoomSite.initWithGensee(AbsRoomSite.java:64)
                                                                                at com.gensee.player.Player.join(Player.java:369)

**Comment by Anjon-github** [comment]
需要在主程序中加入一个32位的so文件

**Comment by kaiyuanshengshichangan** [comment]
@Anjon-github 你的方法确实可行。
 但是，我做插件化开发的初衷是因为有些模块用到了第三方的so,so文件比较多导致应用比较大，所以做成插件化，如果把so文件再向宿主中拷贝一份，那主程序还是比较大的，就没必要做成插件了。

而且上面的问题是在某些手机上报错，有些手机是不报错的，貌似处理器是32位的就不报错

**Comment by Anjon-github** [comment]
你不需要全部拷贝到主程序中，只要找任意一个32位的so文件（当然越小越好了）放到主程序中即可

**Comment by kaiyuanshengshichangan** [comment]
@Anjon-github 非常感谢，虽然不知道什么原因，但是确实可以用了

**Comment by fayou147** [comment]
你的插件中可以添加so文件吗？？我出现了一个java.lang.UnsatisfiedLinkError: Couldn't load ijkffmpeg from loader dalvik.system.DexClassLoader[DexPathList[[zip file "/storage/sdcard0/DynamicLoadHost/app-debug.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]: findLibrary returned null  插件中加so文件有什么需要注意的吗??

**Comment by ray0807** [comment]
@Anjon-github   我拷贝了一个32位的so到主程序了，但是又出现了  
Process: com.ryg.dynamicload.sample.mainhost, PID: 17473 java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.ryg.dynamicload.sample.mainhost/app_pluginlib/libpldroidplayer.so" is too small to be an ELF executable: only found 0 bytes
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                       at java.lang.System.loadLibrary(System.java:989)

我看到了你issue60里面说到了这个问题 ，感觉是解决了 ，但是我还是遇到了这个问题 ！

**Comment by skyson** [comment]
@Anjon-github 用了这个方法可以行的通，不过能问下原因是什么么？

**Comment by hustsqh** [comment]
原因是在64位的android机上，会有32位的虚拟机和64位的虚拟机，在启动apk的时候，虚拟机会根据apk中的so的位数启动对应的虚拟机。

**Comment by xiangguoqiang** [comment]
@fayou147 这个问题搞定了吗？我尝试用插件加载ijkplayer播放器也出现这个问题了

**Comment by cdkd123** [comment]
maybe this would help:
http://blog.csdn.net/ssksuke/article/details/52611689
add config in build
`defaultConfig { 
        ndk {
            abiFilters "armeabi", "mips", "armeabi-v7a"
        }
        packagingOptions {
            exclude "lib/arm64-v8a/librealm-jni.so"
        }
    }`

**Comment by kivenerwang** [comment]
@xiangguoqiang   你动态加载so 出现这个问题 有解决吗？ 使用的是什么方案， 方便说一下吗？

**Comment by pan-haos** [comment]
我也遇到这个问题了，这种时候其实只要保证你的项目里有32位的so，那么即使是64位的也不会再去调用64位的功能除非你的应用也用到了64位的so,
配置如下
`ndk {
            abiFilters "armeabi-v7a"
        }`
然后我的so是放在lib目录下的，所以要在配置文件里配置
`sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }`
