### ISSUE TITLE
宿主启动的插件apk，不能横屏，已横屏就报错了

### ISSUE THREAD

**Issue by jiangfei891111** [singwhatiwanna/dynamic-load-apk#114]
Caused by: java.lang.NullPointerException: Attempt to read from field 'dalvik.system.DexClassLoader com.ryg.dynamicload.internal.DLPluginPackage.classLoader' on a null object reference
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at com.ryg.dynamicload.loader.DLActivityLoader.getClassLoader(DLActivityLoader.java:111)
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at com.ryg.dynamicload.proxy.DLFragmentActivityProxy.getClassLoader(DLFragmentActivityProxy.java:72)
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.support.v4.app.FragmentState.instantiate(Fragment.java:99)
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1835)
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:266)
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at com.ryg.dynamicload.proxy.DLFragmentActivityProxy.onCreate(DLFragmentActivityProxy.java:46)
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6020)
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2259)
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368) 
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3954) 
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:149) 
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1290) 
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5299) 
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
12-28 02:21:12.194 5179-5179/com.example.dynamicliveapk E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by Anjon-github** [comment]
你应该用到了Fragment了吧，在onSaveInstanceState这个方法中，添加 outState.remove("android:support:fragments")

**Comment by waysnotes** [comment]
这个问题解决了吗？我也遇到了
