### ISSUE TITLE
使用dl启动service，然后进入进程管理页面杀掉程序进程，发生空指针

### ISSUE THREAD

**Issue by menshen** [singwhatiwanna/dynamic-load-apk#128]
E/AndroidRuntime(20583): java.lang.RuntimeException: Unable to start service com.ryg.dynamicload.DLProxyService@41c99368 with null: java.lang.NullPointerException
E/AndroidRuntime(20583): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2743)
E/AndroidRuntime(20583): 	at android.app.ActivityThread.access$2100(ActivityThread.java:144)
E/AndroidRuntime(20583): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
E/AndroidRuntime(20583): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(20583): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(20583): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime(20583): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(20583): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(20583): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime(20583): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(20583): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(20583): Caused by: java.lang.NullPointerException
E/AndroidRuntime(20583): 	at com.ryg.dynamicload.internal.DLServiceProxyImpl.init(DLServiceProxyImpl.java:32)
E/AndroidRuntime(20583): 	at com.ryg.dynamicload.DLProxyService.onStartCommand(DLProxyService.java:60)
E/AndroidRuntime(20583): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2726)
E/AndroidRuntime(20583): 	... 10 more

看了一下，应该是因为服务进程被杀掉，系统尝试重启服务，调用服务的onStartCommand
由于是系统启动，所以intent没有带classloader等参数导致
我现在手动的在onStartCommand里面判断了空，直接return了。

**Comment by menshen** [comment]
我在我service的onStartCommand方法中返回START_REDELIVER_INTENT这个问题就没有了，这个问题应该是系统的问题，和dl没关系。
