### ISSUE TITLE
main-plugin-a无法启动

### ISSUE THREAD

**Issue by e-snail** [singwhatiwanna/dynamic-load-apk#145]
启动错误
`java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.ryg.dynamicload.sample.mainplugina/com.ryg.dynamicload.sample.mainplugin.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.ryg.dynamicload.sample.mainplugin.MainActivity" on path: DexPathList[[zip file "/data/app/com.ryg.dynamicload.sample.mainplugina-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ryg.dynamicload.sample.mainplugina-1/lib/arm64, /vendor/lib64, /system/lib64]]

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)

at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)

at android.app.ActivityThread.access$1100(ActivityThread.java:222)

at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)

at android.os.Handler.dispatchMessage(Handler.java:102)

at android.os.Looper.loop(Looper.java:158)

at android.app.ActivityThread.main(ActivityThread.java:7237)

at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ryg.dynamicload.sample.mainplugin.MainActivity" on path: DexPathList[[zip file "/data/app/com.ryg.dynamicload.sample.mainplugina-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ryg.dynamicload.sample.mainplugina-1/lib/arm64, /vendor/lib64, /system/lib64]]

at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

at java.lang.ClassLoader.loadClass(ClassLoader.java:511)

at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

at android.app.Instrumentation.newActivity(Instrumentation.java:1095)

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3084)

at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 

at android.app.ActivityThread.access$1100(ActivityThread.java:222) 

at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) `

**Comment by e-snail** [comment]
插件不能单独启动吗？不能的话怎么调试呢？
