### ISSUE TITLE
main-plugin-b运行出错

### ISSUE THREAD

**Issue by hailongfeng** [singwhatiwanna/dynamic-load-apk#148]
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/dalvikvm: Class resolved by unexpected DEX: Lcom/ryg/dynamicload/sample/mainpluginb/MainActivity;(0x412f7870):0x1e7f610 ref [Lcom/ryg/dynamicload/DLBasePluginActivity;] Lcom/ryg/dynamicload/DLBasePluginActivity;(0x412c88c0):0x1ee77f8
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/dalvikvm: (Lcom/ryg/dynamicload/sample/mainpluginb/MainActivity; had used a different Lcom/ryg/dynamicload/DLBasePluginActivity; during pre-verification)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/dalvikvm: Unable to resolve superclass of Lcom/ryg/dynamicload/sample/mainpluginb/MainActivity; (1372)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/dalvikvm: Link of class 'Lcom/ryg/dynamicload/sample/mainpluginb/MainActivity;' failed
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err: java.lang.ClassNotFoundException: com.ryg.dynamicload.sample.mainpluginb.MainActivity
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at java.lang.Class.classForName(Native Method)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at java.lang.Class.forName(Class.java:217)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at com.ryg.dynamicload.internal.DLPluginManager.loadPluginClass(DLPluginManager.java:397)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at com.ryg.dynamicload.internal.DLPluginManager.startPluginActivityForResult(DLPluginManager.java:246)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at com.ryg.dynamicload.internal.DLPluginManager.startPluginActivity(DLPluginManager.java:216)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at com.ryg.dynamicload.sample.mainhost.MainActivity.onItemClick(MainActivity.java:178)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at android.widget.AdapterView.performItemClick(AdapterView.java:292)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at android.widget.AbsListView.performItemClick(AbsListView.java:1058)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at android.widget.AbsListView$PerformClick.run(AbsListView.java:2514)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at android.widget.AbsListView$1.run(AbsListView.java:3168)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at android.os.Handler.handleCallback(Handler.java:605)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at android.os.Looper.loop(Looper.java:137)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4424)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
10-13 16:49:59.582 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at dalvik.system.NativeStart.main(Native Method)
10-13 16:49:59.587 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err: Caused by: java.lang.NoClassDefFoundError: com/ryg/dynamicload/sample/mainpluginb/MainActivity
10-13 16:49:59.602 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err: 	... 19 more
10-13 16:49:59.602 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err: Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
10-13 16:49:59.602 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at dalvik.system.DexFile.defineClass(Native Method)
10-13 16:49:59.602 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:195)
10-13 16:49:59.602 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at dalvik.system.DexPathList.findClass(DexPathList.java:315)
10-13 16:49:59.602 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:58)
10-13 16:49:59.607 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
10-13 16:49:59.607 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
10-13 16:49:59.607 14701-14701/com.ryg.dynamicload.sample.mainhost W/System.err: 	... 19 more
10-13 16:49:59.632 14701-14703/com.ryg.dynamicload.sample.mainhost D/dalvikvm: GC_CONCURRENT freed 265K, 35% free 6165K/9479K, paused 2ms+3ms

**Comment by LiuHanzhi** [comment]
我也遇到这个问题，在5.0系统上没问题，但是在4.3系统上一运行就报这个错误，求大牛看下如何解决

**Comment by hprostudy** [comment]
@LiuHanzhi 请问问题解决了吗？
