### ISSUE TITLE
andorid 4.4 启动时报错 nullpointer 

### ISSUE THREAD

**Issue by discoy** [singwhatiwanna/dynamic-load-apk#52]
ava.lang.RuntimeException: Unable to start activity ComponentInfo{com.dike.sharetravel/com.ryg.dynamicload.DLProxyFragmentActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
	at android.app.ActivityThread.access$800(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5017)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.ryg.dynamicload.internal.c.a(Unknown Source)
	at com.ryg.dynamicload.DLProxyFragmentActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:5231)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
	... 11 more

**Comment by singwhatiwanna** [comment]
@discoy 调用activity的api请用that关键字
