### ISSUE TITLE
Sample中的DL-sample-main-host点击插件报错

### ISSUE THREAD

**Issue by dxpengyi1990** [singwhatiwanna/dynamic-load-apk#55]
Process: com.ryg.dynamicload.sample.mainhost, PID: 22376
    java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
            at dalvik.system.DexFile.defineClassNative(Native Method)
            at dalvik.system.DexFile.defineClass(DexFile.java:222)
            at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
            at dalvik.system.DexPathList.findClass(DexPathList.java:322)
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
            at com.ryg.dynamicload.internal.DLPluginManager.startPluginActivityForResult(DLPluginManager.java:185)
            at com.ryg.dynamicload.internal.DLPluginManager.startPluginActivity(DLPluginManager.java:150)
            at com.ryg.dynamicload.sample.mainhost.MainActivity.onItemClick(MainActivity.java:164)
            at android.widget.AdapterView.performItemClick(AdapterView.java:299)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:2904)
            at android.widget.AbsListView$3.run(AbsListView.java:3638)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:212)
            at android.app.ActivityThread.main(ActivityThread.java:5151)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
            at dalvik.system.NativeStart.main(Native Method)

开发工具：Android studio
有人说是两个相同类的但是由不同的类加载器加载造成的错误，求解

**Comment by KennyMars** [comment]
宿主的apk包含lib.jar之后，插件就不要把lib.jar编译进去了
